### PR TITLE
new eval callback tracking instances

### PR DESCRIPTION
**Pull request by benjamc**
- custom eval callback
- Instances per episode are logged to evaluations.npz

### CODE REVIEW

**Comment by TheEimer** [comment]
Thanks for implementing this, do you by chance know if this works with the pixel envs?

**Comment by benjamc** [comment]
I don't see why it shouldn't work because checking the instance/context id is independent from the type of state. But I haven't tested it 🤓

**Comment by TheEimer** [comment]
I'm asking because the old one caused problems for pixel based envs

**Comment by TheEimer** [comment]
What about this PR btw, is it still current? We should probably discuss who ends up merging these...

**Comment by benjamc** [comment]
I will close this. The code changes are integrated into my experiment code and this is not relevant for the main repo.

**Pull request closed without merging**
